#
# Copyright (C) 2019 Jianpeng Xiang (1505020109@mail.hnust.edu.cn)
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Smartinfo
LUCI_DEPENDS:=+smartmontools 
PKG_VERSION:=3.2
PKG_RELEASE:=1

PKG_MAINTAINER:=Jianpeng Xiang <1505020109@mail.hnust.edu.cn>
PKG_LICENSE:=GPLv3

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
